### ISSUE TITLE
v4.1.3 introduces a bug related to @actions/artifact

### ISSUE THREAD

**Issue by beeb** [zgosalvez/github-actions-report-lcov#195]
The newest version has a bug which breaks my CI.

![image](https://github.com/zgosalvez/github-actions-report-lcov/assets/703631/6d0321f3-321b-438a-a23f-9c1976248184)

**Comment by sburton84** [comment]
Same for me.

**Comment by zgosalvez** [comment]
On it! 🩴

**Comment by zgosalvez** [comment]
@beeb / @sburton84, please confirm if #196 resolves the bug? I believe you can point your workflow this way:
```yaml
uses: zgosalvez/github-actions-report-lcov@hotfix/artifacts2
```

**Comment by beeb** [comment]
@zgosalvez see below
![image](https://github.com/zgosalvez/github-actions-report-lcov/assets/703631/c47eff7a-338e-4295-9fd4-2894a3cf621f)

**Comment by zgosalvez** [comment]
@beeb, kindly confirm again. I believe I've found the rest of the problems.

**Comment by beeb** [comment]
@zgosalvez all good with the latest fix!

**Comment by zgosalvez** [comment]
Thanks! [v4.1.4](https://github.com/zgosalvez/github-actions-report-lcov/releases/tag/v4.1.4) is now out 🚢
